/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models


import com.squareup.moshi.Json

/**
* This is a running enumeration for the Names of all the Applications that can be Registered
* Values: sUBLIME,vSCODE,jETBRAINS,fIREFOXADDONMV2,fIREFOXADDONMV3,sAFARIEXTENSIONMV2,sAFARIEXTENSIONMV3,pIECESFORDEVELOPERS,pIECESFORDEVELOPERSCLI,oSSERVER,gOOGLECHROMEEXTENSIONMV2,gOOGLECHROMEEXTENSIONMV3,uLTRAEDIT,aTOMPACKAGE,aDOBEILLUSTRATORPIECESCOLORSHARE,mICROSOFTTEAMS,cHATGPT,oBSIDIAN,jUPYTERHUB,vISUALSTUDIO,mICROSOFTEDGE,bRAVE,gOOGLECHAT,sLACK,aZUREDATASTUDIO,oPENSOURCE,uNKNOWN
*/

enum class ApplicationNameEnum(val value: kotlin.String){


    @Json(name = "SUBLIME")
    sUBLIME("SUBLIME"),


    @Json(name = "VS_CODE")
    vSCODE("VS_CODE"),


    @Json(name = "JETBRAINS")
    jETBRAINS("JETBRAINS"),


    @Json(name = "FIREFOX_ADDON_MV2")
    fIREFOXADDONMV2("FIREFOX_ADDON_MV2"),


    @Json(name = "FIREFOX_ADDON_MV3")
    fIREFOXADDONMV3("FIREFOX_ADDON_MV3"),


    @Json(name = "SAFARI_EXTENSION_MV2")
    sAFARIEXTENSIONMV2("SAFARI_EXTENSION_MV2"),


    @Json(name = "SAFARI_EXTENSION_MV3")
    sAFARIEXTENSIONMV3("SAFARI_EXTENSION_MV3"),


    @Json(name = "PIECES_FOR_DEVELOPERS")
    pIECESFORDEVELOPERS("PIECES_FOR_DEVELOPERS"),


    @Json(name = "PIECES_FOR_DEVELOPERS_CLI")
    pIECESFORDEVELOPERSCLI("PIECES_FOR_DEVELOPERS_CLI"),


    @Json(name = "OS_SERVER")
    oSSERVER("OS_SERVER"),


    @Json(name = "GOOGLE_CHROME_EXTENSION_MV2")
    gOOGLECHROMEEXTENSIONMV2("GOOGLE_CHROME_EXTENSION_MV2"),


    @Json(name = "GOOGLE_CHROME_EXTENSION_MV3")
    gOOGLECHROMEEXTENSIONMV3("GOOGLE_CHROME_EXTENSION_MV3"),


    @Json(name = "ULTRA_EDIT")
    uLTRAEDIT("ULTRA_EDIT"),


    @Json(name = "ATOM_PACKAGE")
    aTOMPACKAGE("ATOM_PACKAGE"),


    @Json(name = "ADOBE_ILLUSTRATOR_PIECES_COLOR_SHARE")
    aDOBEILLUSTRATORPIECESCOLORSHARE("ADOBE_ILLUSTRATOR_PIECES_COLOR_SHARE"),


    @Json(name = "MICROSOFT_TEAMS")
    mICROSOFTTEAMS("MICROSOFT_TEAMS"),


    @Json(name = "CHAT_GPT")
    cHATGPT("CHAT_GPT"),


    @Json(name = "OBSIDIAN")
    oBSIDIAN("OBSIDIAN"),


    @Json(name = "JUPYTER_HUB")
    jUPYTERHUB("JUPYTER_HUB"),


    @Json(name = "VISUAL_STUDIO")
    vISUALSTUDIO("VISUAL_STUDIO"),


    @Json(name = "MICROSOFT_EDGE")
    mICROSOFTEDGE("MICROSOFT_EDGE"),


    @Json(name = "BRAVE")
    bRAVE("BRAVE"),


    @Json(name = "GOOGLE_CHAT")
    gOOGLECHAT("GOOGLE_CHAT"),


    @Json(name = "SLACK")
    sLACK("SLACK"),


    @Json(name = "AZURE_DATA_STUDIO")
    aZUREDATASTUDIO("AZURE_DATA_STUDIO"),


    @Json(name = "OPEN_SOURCE")
    oPENSOURCE("OPEN_SOURCE"),


    @Json(name = "UNKNOWN")
    uNKNOWN("UNKNOWN");



    /**
    This override toString avoids using the enum var name and uses the actual api value instead.
    In cases the var name and value are different, the client would send incorrect enums to the server.
    **/
    override fun toString(): String {
        return value
    }

}

