/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.FlattenedAsset
import org.openapitools.client.models.Format

import com.squareup.moshi.Json

/**
 * A collection of Formats for a specific asset.  Formats used at runtime have the capability (and are likely cross-polinated) with a deep reference to the asset meaning asset is not a String but actually a ReferencedAsset, which at minimum contains a id representing the asset as well as a reference which is undefined/null or a FlattenedAsset
 * @param asset 
 * @param schema 
 * @param iterable 
 */

data class AssetFormats (
    @Json(name = "asset")
    val asset: FlattenedAsset,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "iterable")
    val iterable: kotlin.collections.List<Format>? = null
)

