/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.GroupedTimestamp

import com.squareup.moshi.Json

/**
 * if you want a range between you can use from && to.  if you want anything before, use to and NO from.  if you want anything after, use from and NO to.
 * @param schema 
 * @param from 
 * @param to 
 * @param between 
 */

data class AssetFilterTimestamp (
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "from")
    val from: GroupedTimestamp? = null,
    @Json(name = "to")
    val to: GroupedTimestamp? = null,
    @Json(name = "between")
    val between: kotlin.Boolean? = null
)

