/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.AssetFilter
import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.FilterOperationTypeEnum

import com.squareup.moshi.Json

/**
 * 
 * @param iterable 
 * @param schema 
 * @param type 
 */

data class AssetFilters (
    @Json(name = "iterable")
    val iterable: kotlin.collections.List<AssetFilter>,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "type")
    val type: FilterOperationTypeEnum? = null
)

