/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models

import org.piecesapp.client.models.Application
import org.piecesapp.client.models.EmbeddedModelSchema
import org.piecesapp.client.models.Health
import org.piecesapp.client.models.UserProfile

import com.squareup.moshi.Json

/**
 * A Context that is returned from almost all calls to the ContextAPI
 * @param os This is th UUID of the OS that this context is currently connected to. This attempts to be the same as Segment's anonmyousId feild. It is attempted to be set at initial installation at Pieces/.identity/.os
 * @param application 
 * @param health 
 * @param schema 
 * @param user 
 */

data class Context (
    /* This is th UUID of the OS that this context is currently connected to. This attempts to be the same as Segment's anonmyousId feild. It is attempted to be set at initial installation at Pieces/.identity/.os */
    @Json(name = "os")
    val os: kotlin.String,
    @Json(name = "application")
    val application: Application,
    @Json(name = "health")
    val health: Health,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "user")
    val user: UserProfile? = null
)

