/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.FlattenedConversationMessages

import com.squareup.moshi.Json

/**
 * This is the context used for grounding the ml models with reguard to a conversation.
 * @param schema 
 * @param messages 
 */

data class ConversationGrounding (
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "messages")
    val messages: FlattenedConversationMessages? = null
)

