/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchemaSemanticVersionEnum

import com.squareup.moshi.Json

/**
 * This is a model that will keep track of all of our version related to our models. ie (1) the database migration and (2) the global semantic version of the api.
 * @param migration this is the current database version that this model was used for.
 * @param semantic 
 */

data class EmbeddedModelSchema (
    /* this is the current database version that this model was used for. */
    @Json(name = "migration")
    val migration: kotlin.Int,
    @Json(name = "semantic")
    val semantic: EmbeddedModelSchemaSemanticVersionEnum
)

