/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.ReferencedTag
import org.openapitools.client.models.ReferencedWebsite

import com.squareup.moshi.Json

/**
 * This is a shared input model for all the exists endpoints: /tags/exists : if the tag exists you will have a defined tag:ReferencedTag, if not then it doesnt exist. /websites/exists: if the url exists you will have a defined website:ReferencedWebsite, if not then it doesnt exist.
 * @param schema 
 * @param website 
 * @param tag 
 */

data class ExistingMetadata (
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "website")
    val website: ReferencedWebsite? = null,
    @Json(name = "tag")
    val tag: ReferencedTag? = null
)

