/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models

import org.piecesapp.client.models.EmbeddedModelSchema
import org.piecesapp.client.models.TransferableBytes
import org.piecesapp.client.models.TransferableString

import com.squareup.moshi.Json

/**
 * This describes a FileFormat. If you need meta data you can get all of that from your format wrapper.
 * @param schema 
 * @param bytes 
 * @param string 
 */

data class FileFormat (
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "bytes")
    val bytes: TransferableBytes? = null,
    @Json(name = "string")
    val string: TransferableString? = null
)

