/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema

import com.squareup.moshi.Json

/**
 * This is a FlattenedUserProfile that includes information that is not sensative in relation to a user.
 * @param id this is the uuid that identifies a user.
 * @param schema 
 * @param email 
 * @param name 
 * @param username 
 * @param picture 
 * @param vanityname 
 */

data class FlattenedUserProfile (
    /* this is the uuid that identifies a user. */
    @Json(name = "id")
    val id: kotlin.String,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "email")
    val email: kotlin.String? = null,
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "username")
    val username: kotlin.String? = null,
    @Json(name = "picture")
    val picture: kotlin.String? = null,
    @Json(name = "vanityname")
    val vanityname: kotlin.String? = null
)

