/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.FlattenedOCRAnalysis

import com.squareup.moshi.Json

/**
 * 
 * @param id 
 * @param analysis this is a reference to our (parent)analysis
 * @param schema 
 * @param ocr 
 */

data class FlattenedImageAnalysis (
    @Json(name = "id")
    val id: kotlin.String,
    /* this is a reference to our (parent)analysis */
    @Json(name = "analysis")
    val analysis: kotlin.String,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "ocr")
    val ocr: FlattenedOCRAnalysis? = null
)

