/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.GroupedTimestamp
import org.openapitools.client.models.MechanismEnum
import org.openapitools.client.models.ReferencedAsset
import org.openapitools.client.models.Score
import org.openapitools.client.models.SensitiveCategoryEnum
import org.openapitools.client.models.SensitiveMetadata
import org.openapitools.client.models.SensitiveSeverityEnum

import com.squareup.moshi.Json

/**
 * This is a dereferenced representation of a sensitive pieces of data.
 * @param id 
 * @param created 
 * @param updated 
 * @param asset 
 * @param text 
 * @param mechanism 
 * @param category 
 * @param severity 
 * @param name 
 * @param description 
 * @param schema 
 * @param deleted 
 * @param metadata 
 * @param interactions This is an optional value that will keep track of the number of times this has been interacted with.
 * @param score 
 */

data class FlattenedSensitive (
    @Json(name = "id")
    val id: kotlin.String,
    @Json(name = "created")
    val created: GroupedTimestamp,
    @Json(name = "updated")
    val updated: GroupedTimestamp,
    @Json(name = "asset")
    val asset: ReferencedAsset,
    @Json(name = "text")
    val text: kotlin.String,
    @Json(name = "mechanism")
    val mechanism: MechanismEnum,
    @Json(name = "category")
    val category: SensitiveCategoryEnum,
    @Json(name = "severity")
    val severity: SensitiveSeverityEnum,
    @Json(name = "name")
    val name: kotlin.String,
    @Json(name = "description")
    val description: kotlin.String,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "deleted")
    val deleted: GroupedTimestamp? = null,
    @Json(name = "metadata")
    val metadata: SensitiveMetadata? = null,
    /* This is an optional value that will keep track of the number of times this has been interacted with. */
    @Json(name = "interactions")
    val interactions: kotlin.Int? = null,
    @Json(name = "score")
    val score: Score? = null
)

