/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.GroupedTimestamp
import org.openapitools.client.models.PlatformEnum
import org.openapitools.client.models.ReferencedAnchor
import org.openapitools.client.models.Score

import com.squareup.moshi.Json

/**
 * 
 * @param id 
 * @param fullpath This is the text of the path.
 * @param created 
 * @param updated 
 * @param anchor 
 * @param schema 
 * @param verified 
 * @param deleted 
 * @param platform 
 * @param score 
 */

data class FlattenedAnchorPoint (
    @Json(name = "id")
    val id: kotlin.String,
    /* This is the text of the path. */
    @Json(name = "fullpath")
    val fullpath: kotlin.String,
    @Json(name = "created")
    val created: GroupedTimestamp,
    @Json(name = "updated")
    val updated: GroupedTimestamp,
    @Json(name = "anchor")
    val anchor: ReferencedAnchor,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "verified")
    val verified: kotlin.Boolean? = null,
    @Json(name = "deleted")
    val deleted: GroupedTimestamp? = null,
    @Json(name = "platform")
    val platform: PlatformEnum? = null,
    @Json(name = "score")
    val score: Score? = null
)

