/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.GraphicalOCRDescriptiveStatisticsConfidence

import com.squareup.moshi.Json

/**
 * Model for monitoring and evaluating the OCR feature
 * @param asset 
 * @param user 
 * @param model 
 * @param created 
 * @param os 
 * @param confidence 
 * @param duration 
 * @param schema 
 */

data class GraphicalOCRDescriptiveStatistics (
    @Json(name = "asset")
    val asset: kotlin.String,
    @Json(name = "user")
    val user: kotlin.String,
    @Json(name = "model")
    val model: kotlin.String,
    @Json(name = "created")
    val created: kotlin.String,
    @Json(name = "os")
    val os: kotlin.String,
    @Json(name = "confidence")
    val confidence: GraphicalOCRDescriptiveStatisticsConfidence,
    @Json(name = "duration")
    val duration: kotlin.String,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null
)

