/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models

import org.piecesapp.client.models.LanguageClassifierDistribution

import com.squareup.moshi.Json

/**
 * Strongly-typed returnable class for the programming language ML classifier.
 * @param language 
 * @param distribution 
 * @param normalized this is the string right before tokenization.
 * @param tokens this is the tokenized representation of the string.
 */

data class LanguageClassifierReturnable (
    @Json(name = "language")
    val language: kotlin.String,
    @Json(name = "distribution")
    val distribution: LanguageClassifierDistribution,
    /* this is the string right before tokenization. */
    @Json(name = "normalized")
    val normalized: kotlin.String,
    /* this is the tokenized representation of the string. */
    @Json(name = "tokens")
    val tokens: kotlin.collections.List<java.math.BigDecimal>
)

