/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models

import org.piecesapp.client.models.AccessEnum
import org.piecesapp.client.models.EmbeddedModelSchema
import org.piecesapp.client.models.SeededUser

import com.squareup.moshi.Json

/**
 * This is the incoming linkify model.  if access is PRIVATE then please provide and array of users to enable the link for.  Assumption, all assets are already backed up to the cloud. 
 * @param assets This is an array or string that represents an already backed up asset. That will be added to a collection.
 * @param access 
 * @param schema 
 * @param users this is an array of users.
 * @param name optionally can give the collection a name if you want.
 */

data class LinkifyMultiple (
    /* This is an array or string that represents an already backed up asset. That will be added to a collection. */
    @Json(name = "assets")
    val assets: kotlin.collections.List<kotlin.String>,
    @Json(name = "access")
    val access: AccessEnum,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    /* this is an array of users. */
    @Json(name = "users")
    val users: kotlin.collections.List<SeededUser>? = null,
    /* optionally can give the collection a name if you want. */
    @Json(name = "name")
    val name: kotlin.String? = null
)

