/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models


import com.squareup.moshi.Json

/**
 * Strongly-typed returnable class for link extraction from a text asset.
 * @param urls 
 * @param emails 
 * @param users 
 */

data class LinkExtractionReturnable (
    @Json(name = "urls")
    val urls: kotlin.collections.List<kotlin.String>,
    @Json(name = "emails")
    val emails: kotlin.collections.List<kotlin.String>,
    @Json(name = "users")
    val users: kotlin.collections.List<kotlin.String>
)

