/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema

import com.squareup.moshi.Json

/**
 * TODO add additional properties. TODO eventually modify this model to look like the response from Mailgun.
 * @param messageId This is the id given to us from mailgun when the email was sent successfully.
 * @param schema 
 */

data class MailgunMetadata (
    /* This is the id given to us from mailgun when the email was sent successfully. */
    @Json(name = "messageId")
    val messageId: kotlin.String,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null
)

