/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
* This will let us know how an asset was uploaded.  MANUAL: this is an event such as a user driven send to pieces, or a paste to pieces.  RECOMMENDED: This is an event that was initiall recommended via the suggestion flow, and a user decided totake the recommendation.  AUTOMATIC: This is not user driven at all and the asset was automatically uploaded via the suggestion flow. or other methods.  INTERNAL: This is an undelete able enum used for internal use only.
* Values: mANUAL,rECOMMENDED,aUTOMATIC,iNTERNAL,dELETED
*/

enum class MechanismEnum(val value: kotlin.String){


    @Json(name = "MANUAL")
    mANUAL("MANUAL"),


    @Json(name = "RECOMMENDED")
    rECOMMENDED("RECOMMENDED"),


    @Json(name = "AUTOMATIC")
    aUTOMATIC("AUTOMATIC"),


    @Json(name = "INTERNAL")
    iNTERNAL("INTERNAL"),


    @Json(name = "DELETED")
    dELETED("DELETED");



    /**
    This override toString avoids using the enum var name and uses the actual api value instead.
    In cases the var name and value are different, the client would send incorrect enums to the server.
    **/
    override fun toString(): String {
        return value
    }

}

