/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.ModelDownloadProgressStatusEnum

import com.squareup.moshi.Json

/**
 * This is the model that is sent over our ws for streaming the progress of a model that is being downloaded.  can eventually add a number that display the percent downloaded an so on.(this is called percent 0-100)
 * @param schema 
 * @param status 
 * @param percentage Optionally if the download is in progress you will recieve a download percent(from 0-100).
 */

data class ModelDownloadProgress (
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "status")
    val status: ModelDownloadProgressStatusEnum? = null,
    /* Optionally if the download is in progress you will recieve a download percent(from 0-100). */
    @Json(name = "percentage")
    val percentage: java.math.BigDecimal? = null
)

