/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
* This describes the type of a node ie an asset, tag, website, format... ETC
* Values: tAG,wEBSITE,fORMAT,aSSET
*/

enum class NodeTypeEnum(val value: kotlin.String){


    @Json(name = "TAG")
    tAG("TAG"),


    @Json(name = "WEBSITE")
    wEBSITE("WEBSITE"),


    @Json(name = "FORMAT")
    fORMAT("FORMAT"),


    @Json(name = "ASSET")
    aSSET("ASSET");



    /**
    This override toString avoids using the enum var name and uses the actual api value instead.
    In cases the var name and value are different, the client would send incorrect enums to the server.
    **/
    override fun toString(): String {
        return value
    }

}

