/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.OAuthAccount
import org.openapitools.client.models.OAuthToken

import com.squareup.moshi.Json

/**
 * A model to group all of the properties associated with OAuthGroup
 * @param token 
 * @param account 
 */

data class OAuthGroup (
    @Json(name = "token")
    val token: OAuthToken? = null,
    @Json(name = "account")
    val account: OAuthAccount? = null
)

