/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.Format
import org.openapitools.client.models.Model

import com.squareup.moshi.Json

/**
 * This is the data collected during the ocr analysis of an image.
 * @param id 
 * @param raw 
 * @param hocr 
 * @param image this is a reference the the imageAnalysis.
 * @param model 
 * @param schema 
 */

data class OCRAnalysis (
    @Json(name = "id")
    val id: kotlin.String,
    @Json(name = "raw")
    val raw: Format,
    @Json(name = "hocr")
    val hocr: Format,
    /* this is a reference the the imageAnalysis. */
    @Json(name = "image")
    val image: kotlin.String,
    @Json(name = "model")
    val model: Model,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null
)

