/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.GroupedTimestamp
import org.openapitools.client.models.PersonAccessScopedEnum

import com.squareup.moshi.Json

/**
 * if scoped is provided will let us know what level of permission(access) this specific person has in relation to what scope.(collection, asset,...etc)  in the future will expand to global (with its own enumeration for a global entire project/cloud scope)
 * @param schema 
 * @param scoped 
 * @param deleted 
 */

data class PersonAccess (
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "scoped")
    val scoped: PersonAccessScopedEnum? = null,
    @Json(name = "deleted")
    val deleted: GroupedTimestamp? = null
)

