/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.ExternallySourcedEnum
import org.openapitools.client.models.MailgunMetadata

import com.squareup.moshi.Json

/**
 * This is all optional properties around the most basic information around a non-pieces user.  A Basic type will NOT have a scope as it is not an actual pieces user.
 * @param schema 
 * @param username username or twitter handle...etc
 * @param name This is the name of the basic user.
 * @param picture this is a url picture representation of a user.
 * @param email an email that was extracted.
 * @param sourced 
 * @param url This is a specific url that this basic user came from.
 * @param mailgun 
 */

data class PersonBasicType (
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    /* username or twitter handle...etc */
    @Json(name = "username")
    val username: kotlin.String? = null,
    /* This is the name of the basic user. */
    @Json(name = "name")
    val name: kotlin.String? = null,
    /* this is a url picture representation of a user. */
    @Json(name = "picture")
    val picture: kotlin.String? = null,
    /* an email that was extracted. */
    @Json(name = "email")
    val email: kotlin.String? = null,
    @Json(name = "sourced")
    val sourced: ExternallySourcedEnum? = null,
    /* This is a specific url that this basic user came from. */
    @Json(name = "url")
    val url: kotlin.String? = null,
    @Json(name = "mailgun")
    val mailgun: MailgunMetadata? = null
)

