/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models

import org.piecesapp.client.models.EmbeddedModelSchema
import org.piecesapp.client.models.FlattenedAssets

import com.squareup.moshi.Json

/**
 * This is a model of all optional properties, that will get returned from /assets/pseudo.
 * @param schema 
 * @param identifiers 
 */

data class PseudoAssets (
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "identifiers")
    val identifiers: FlattenedAssets? = null
)

