/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
* This is a specific Enum used for the QGPT Stream.
* Values: cANCELED,iNITIALIZED,iNMinusPROGRESS,cOMPLETED,fAILED,uNKNOWN,sTOPPED,rESET
*/

enum class QGPTStreamEnum(val value: kotlin.String){


    @Json(name = "CANCELED")
    cANCELED("CANCELED"),


    @Json(name = "INITIALIZED")
    iNITIALIZED("INITIALIZED"),


    @Json(name = "IN-PROGRESS")
    iNMinusPROGRESS("IN-PROGRESS"),


    @Json(name = "COMPLETED")
    cOMPLETED("COMPLETED"),


    @Json(name = "FAILED")
    fAILED("FAILED"),


    @Json(name = "UNKNOWN")
    uNKNOWN("UNKNOWN"),


    @Json(name = "STOPPED")
    sTOPPED("STOPPED"),


    @Json(name = "RESET")
    rESET("RESET");



    /**
    This override toString avoids using the enum var name and uses the actual api value instead.
    In cases the var name and value are different, the client would send incorrect enums to the server.
    **/
    override fun toString(): String {
        return value
    }

}

