/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.QGPTQuestionAnswer
import org.openapitools.client.models.RelevantQGPTSeeds

import com.squareup.moshi.Json

/**
 * Query is your hints question. Relevant is the relevant snippets. Answer is the previous answer.(that we are asking a hint up for.)  Query and Answer are both optional here because, you may pass over relevant snippets over ahead of hand if you already have them to answer your questions.
 * @param relevant 
 * @param query 
 * @param answer 
 * @param application optional application id
 * @param model optional model id
 */

data class QGPTHintsInput (
    @Json(name = "relevant")
    val relevant: RelevantQGPTSeeds,
    @Json(name = "query")
    val query: kotlin.String? = null,
    @Json(name = "answer")
    val answer: QGPTQuestionAnswer? = null,
    /* optional application id */
    @Json(name = "application")
    val application: kotlin.String? = null,
    /* optional model id */
    @Json(name = "model")
    val model: kotlin.String? = null
)

