/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.Edges
import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.Embeddings
import org.openapitools.client.models.GroupedTimestamp

import com.squareup.moshi.Json

/**
 * A relationship expresses a graph of like types, to build a relationship graph.   To get the type of relationship, this is for ie Asset, tag, website, format ...etc, you will need to iterate through the edges and get the root or you can just get the first edge's type as a relationship can only be expressed through same type
 * @param id 
 * @param embeddings 
 * @param edges 
 * @param created 
 * @param updated 
 * @param schema 
 * @param deleted 
 */

data class Relationship (
    @Json(name = "id")
    val id: kotlin.String,
    @Json(name = "embeddings")
    val embeddings: Embeddings,
    @Json(name = "edges")
    val edges: Edges,
    @Json(name = "created")
    val created: GroupedTimestamp,
    @Json(name = "updated")
    val updated: GroupedTimestamp,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "deleted")
    val deleted: GroupedTimestamp? = null
)

