/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.Asset
import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.SearchedMatchEnum

import com.squareup.moshi.Json

/**
 * This is a modle that will represent a searched asset!
 * @param exact 
 * @param score 
 * @param match 
 * @param identifier This is the uuid of the asset.
 * @param schema 
 * @param asset 
 * @param pseudo If this is a pseudo asset that was also returned.
 */

data class SearchedAsset (
    @Json(name = "exact")
    val exact: kotlin.Boolean,
    @Json(name = "score")
    val score: java.math.BigDecimal,
    @Json(name = "match")
    val match: SearchedMatchEnum,
    /* This is the uuid of the asset. */
    @Json(name = "identifier")
    val identifier: kotlin.String,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "asset")
    val asset: Asset? = null,
    /* If this is a pseudo asset that was also returned. */
    @Json(name = "pseudo")
    val pseudo: kotlin.Boolean? = null
)

