/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.Application
import org.openapitools.client.models.AvailableFormats
import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.SeededAssetMetadata
import org.openapitools.client.models.SeededFormat

import com.squareup.moshi.Json

/**
 * This is seed data that will be come an asset.  discovered: if set to true this seededAsset was discovered using one of our discovery endpoints.  pseudo: if this is an asset that a user did NOT explicitly save.  available: This is a model that is used within our '/assets/draft' endpoint that will emitt a seed with all the available format that one can generate based on the original seed that was passed in. ie if a png was passed in, we may  say that there is a text/code format available. If available formats is passed into the '/assets/create' we will short curcuit certain operations to speed up the process, for instance, if we determine that there is no text within this image then there is no sense in running ocr. 
 * @param application 
 * @param format 
 * @param schema 
 * @param metadata 
 * @param discovered 
 * @param available 
 * @param pseudo 
 */

data class SeededAsset (
    @Json(name = "application")
    val application: Application,
    @Json(name = "format")
    val format: SeededFormat,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "metadata")
    val metadata: SeededAssetMetadata? = null,
    @Json(name = "discovered")
    val discovered: kotlin.Boolean? = null,
    @Json(name = "available")
    val available: AvailableFormats? = null,
    @Json(name = "pseudo")
    val pseudo: kotlin.Boolean? = null
)

