/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.ClassificationSpecificEnum
import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.SeededFormat

import com.squareup.moshi.Json

/**
 * A SeededUEAsset is the minimum data sent from UE required to create an asset within Pieces.  Fragment & file are both optional properties however we will throw an internal error if both fragment and file are passed through or if both are undefined.
 * @param format 
 * @param schema 
 * @param name (optional) name is the name of the file
 * @param ext 
 * @param description 
 */

data class SeededUltraSuiteAsset (
    @Json(name = "format")
    val format: SeededFormat,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    /* (optional) name is the name of the file */
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "ext")
    val ext: ClassificationSpecificEnum? = null,
    @Json(name = "description")
    val description: kotlin.String? = null
)

