/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models

import org.piecesapp.client.models.EmbeddedModelSchema
import org.piecesapp.client.models.MechanismEnum
import org.piecesapp.client.models.SensitiveCategoryEnum
import org.piecesapp.client.models.SensitiveMetadata
import org.piecesapp.client.models.SensitiveSeverityEnum

import com.squareup.moshi.Json

/**
 * This is the seededSensitive, this does not have an id yet as we will add it on the server side.  can optionally pass in our mechanism here, as the default will be manual unless specified.  TODO consider updating these asset,format to referenced Models
 * @param asset 
 * @param text this is the string representative of the sensative piece of data.
 * @param category 
 * @param severity 
 * @param name 
 * @param description 
 * @param schema 
 * @param mechanism 
 * @param metadata 
 */

data class SeededSensitive (
    @Json(name = "asset")
    val asset: kotlin.String,
    /* this is the string representative of the sensative piece of data. */
    @Json(name = "text")
    val text: kotlin.String,
    @Json(name = "category")
    val category: SensitiveCategoryEnum,
    @Json(name = "severity")
    val severity: SensitiveSeverityEnum,
    @Json(name = "name")
    val name: kotlin.String,
    @Json(name = "description")
    val description: kotlin.String,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "mechanism")
    val mechanism: MechanismEnum? = null,
    @Json(name = "metadata")
    val metadata: SensitiveMetadata? = null
)

