/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.MechanismEnum
import org.openapitools.client.models.PersonAccess
import org.openapitools.client.models.PersonModel
import org.openapitools.client.models.PersonType
import org.openapitools.client.models.SeededAnnotation

import com.squareup.moshi.Json

/**
 * This is a per-cursor to a full person.  Will throw an error, if asset is passed in but acces.scope is undefined.  can optionally pass in our mechanism here, as the default will be manual unless specified.  TODO consider updating these asset, format to referenced Models  Note: model, access, mechanism will only be added if the asset is passed in.
 * @param type 
 * @param schema 
 * @param asset 
 * @param mechanism 
 * @param access 
 * @param model 
 * @param annotations 
 */

data class SeededPerson (
    @Json(name = "type")
    val type: PersonType,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "asset")
    val asset: kotlin.String? = null,
    @Json(name = "mechanism")
    val mechanism: MechanismEnum? = null,
    @Json(name = "access")
    val access: PersonAccess? = null,
    @Json(name = "model")
    val model: PersonModel? = null,
    @Json(name = "annotations")
    val annotations: kotlin.collections.List<SeededAnnotation>? = null
)

