/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models

import org.piecesapp.client.models.EmbeddedModelSchema
import org.piecesapp.client.models.SeededConnectorAsset

import com.squareup.moshi.Json

/**
 * A encompasing creation object that can be utilized to create either an asset or a format.
 * @param schema 
 * @param asset 
 */

data class SeededConnectorCreation (
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "asset")
    val asset: SeededConnectorAsset? = null
)

