/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models

import org.piecesapp.client.models.EmbeddedModelSchema
import org.piecesapp.client.models.ReferencedFormat
import org.piecesapp.client.models.TrackedFormatEventIdentifierDescriptionPairs
import org.piecesapp.client.models.TrackedFormatEventMetadata

import com.squareup.moshi.Json

/**
 * Again this is a model designed to be sent over to a context server to be built and then sent along to segment. 
 * @param identifierDescriptionPair 
 * @param format 
 * @param schema 
 * @param metadata 
 */

data class SeededTrackedFormatEvent (
    @Json(name = "identifier_description_pair")
    val identifierDescriptionPair: TrackedFormatEventIdentifierDescriptionPairs,
    @Json(name = "format")
    val format: ReferencedFormat,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "metadata")
    val metadata: TrackedFormatEventMetadata? = null
)

