/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models

import org.piecesapp.client.models.EmbeddedModelSchema
import org.piecesapp.client.models.SeededDiscoverableAsset
import org.piecesapp.client.models.TLPDirectedDiscoveryFilters

import com.squareup.moshi.Json

/**
 * Assumption: filters imposed in this model can be overwritten by passing them in SeededDiscoverableAsset
 * @param application application id.
 * @param iterable This is an iterable of already snippitized snippets that we will compare && cluster.
 * @param schema 
 * @param filters 
 */

data class SeededDiscoverableAssets (
    /* application id. */
    @Json(name = "application")
    val application: kotlin.String,
    /* This is an iterable of already snippitized snippets that we will compare && cluster. */
    @Json(name = "iterable")
    val iterable: kotlin.collections.List<SeededDiscoverableAsset>,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "filters")
    val filters: TLPDirectedDiscoveryFilters? = null
)

