/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models

import org.piecesapp.client.models.EmbeddedModelSchema
import org.piecesapp.client.models.MechanismEnum
import org.piecesapp.client.models.SeededAnchor
import org.piecesapp.client.models.SeededAnnotation
import org.piecesapp.client.models.SeededAssetSensitive
import org.piecesapp.client.models.SeededAssetTag
import org.piecesapp.client.models.SeededAssetWebsite
import org.piecesapp.client.models.SeededHint
import org.piecesapp.client.models.SeededPerson

import com.squareup.moshi.Json

/**
 * This is optional metadata sent with the SeededAsset and other SeededAssets ie (UE, Jetbrains...)  Note: if a user/develop didnt explicitly state a mechanism we will default to manual(user Driven only)
 * @param schema 
 * @param name This is the name of the asset.
 * @param mechanism 
 * @param tags (optional) can add some tags to associate to this asset.
 * @param websites 
 * @param sensitives 
 * @param persons 
 * @param annotations 
 * @param hints 
 * @param anchors 
 */

data class SeededAssetMetadata (
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    /* This is the name of the asset. */
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "mechanism")
    val mechanism: MechanismEnum? = null,
    /* (optional) can add some tags to associate to this asset. */
    @Json(name = "tags")
    val tags: kotlin.collections.List<SeededAssetTag>? = null,
    @Json(name = "websites")
    val websites: kotlin.collections.List<SeededAssetWebsite>? = null,
    @Json(name = "sensitives")
    val sensitives: kotlin.collections.List<SeededAssetSensitive>? = null,
    @Json(name = "persons")
    val persons: kotlin.collections.List<SeededPerson>? = null,
    @Json(name = "annotations")
    val annotations: kotlin.collections.List<SeededAnnotation>? = null,
    @Json(name = "hints")
    val hints: kotlin.collections.List<SeededHint>? = null,
    @Json(name = "anchors")
    val anchors: kotlin.collections.List<SeededAnchor>? = null
)

