/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.SeededClassification
import org.openapitools.client.models.SeededFile
import org.openapitools.client.models.SeededFragment

import com.squareup.moshi.Json

/**
 * This is seeded data that will be come a format.  We will throw an Error if, 1) file and fragment are both defined, 2) file and fragment are both null.  if this is being used within the /assets/create endpoint or the /{application}/create endpoint, we will not take the classificaiton into account, as it is only used in the syntax highlighting related endpoints.That being said if you do want to override your classification, please look at the metadata within the file or the fragment.
 * @param schema 
 * @param file 
 * @param fragment 
 * @param classification 
 */

data class SeededFormat (
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "file")
    val file: SeededFile? = null,
    @Json(name = "fragment")
    val fragment: SeededFragment? = null,
    @Json(name = "classification")
    val classification: SeededClassification? = null
)

