/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.MechanismEnum
import org.openapitools.client.models.TagCategoryEnum

import com.squareup.moshi.Json

/**
 * 
 * @param text This is the description of the tag.
 * @param asset this is a uuid that references an asset.
 * @param schema 
 * @param mechanism 
 * @param format (optionally) you can attach a tag to a format. so when you delete a format this tag will get removed from the asset as well.
 * @param category 
 */

data class SeededDiscoverableRelatedTag (
    /* This is the description of the tag. */
    @Json(name = "text")
    val text: kotlin.String,
    /* this is a uuid that references an asset. */
    @Json(name = "asset")
    val asset: kotlin.String,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "mechanism")
    val mechanism: MechanismEnum? = null,
    /* (optionally) you can attach a tag to a format. so when you delete a format this tag will get removed from the asset as well. */
    @Json(name = "format")
    val format: kotlin.String? = null,
    @Json(name = "category")
    val category: TagCategoryEnum? = null
)

