/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.TextMatch

import com.squareup.moshi.Json

/**
 * This is optional metatdata attached to a sensitive piece of data.
 * @param schema 
 * @param match 
 * @param entropy entropy of the sensitive
 */

data class SensitiveMetadata (
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "match")
    val match: TextMatch? = null,
    /* entropy of the sensitive */
    @Json(name = "entropy")
    val entropy: java.math.BigDecimal? = null
)

