/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models

import org.piecesapp.client.models.EmbeddedModelSchema
import org.piecesapp.client.models.SeededConnectorCreation

import com.squareup.moshi.Json

/**
 * This is the target that was sent to pieces. This will return the string that represents this coppied || pasted asset. This will also send along the SeededConnectorCreation and will send along the vector that we created based on the seed.
 * @param seed 
 * @param vector This is the vector representation of this target that we generated.
 * @param schema 
 */

data class SuggestionTarget (
    @Json(name = "seed")
    val seed: SeededConnectorCreation,
    /* This is the vector representation of this target that we generated. */
    @Json(name = "vector")
    val vector: kotlin.Int,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null
)

