/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema

import com.squareup.moshi.Json

/**
 * 
 * @param name 
 * @param parentColor 
 * @param delta 
 * @param hex 
 * @param schema 
 */

data class TLPCodeSnippetTagifyNamedColor (
    @Json(name = "name")
    val name: kotlin.String,
    @Json(name = "parentColor")
    val parentColor: kotlin.String,
    @Json(name = "delta")
    val delta: java.math.BigDecimal,
    @Json(name = "hex")
    val hex: kotlin.String,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null
)

