/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.TLPCodeFragmentClassification
import org.openapitools.client.models.TLPCodeFragmentDescription
import org.openapitools.client.models.TLPCodeFragmentReclassification
import org.openapitools.client.models.TLPCodeFragmentStatistics
import org.openapitools.client.models.TLPCodeFragmentTagify
import org.openapitools.client.models.TLPCodeSnippetSuggestedInteractions

import com.squareup.moshi.Json

/**
 * 
 * @param schema 
 * @param statistics 
 * @param classification 
 * @param reclassification 
 * @param suggested 
 * @param tagify 
 * @param description 
 */

data class TLPCodeSnippetAnalytics (
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "statistics")
    val statistics: TLPCodeFragmentStatistics? = null,
    @Json(name = "classification")
    val classification: TLPCodeFragmentClassification? = null,
    @Json(name = "reclassification")
    val reclassification: TLPCodeFragmentReclassification? = null,
    @Json(name = "suggested")
    val suggested: TLPCodeSnippetSuggestedInteractions? = null,
    @Json(name = "tagify")
    val tagify: TLPCodeFragmentTagify? = null,
    @Json(name = "description")
    val description: TLPCodeFragmentDescription? = null
)

