/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param distribution 
 * @param inferredDistribution 
 * @param tags 
 * @param inferredTags 
 */

data class TLPCodeSnippetTagifyCodeReturnable (
    @Json(name = "distribution")
    val distribution: kotlin.collections.List<java.math.BigDecimal>,
    @Json(name = "inferred_distribution")
    val inferredDistribution: kotlin.collections.List<java.math.BigDecimal>,
    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>,
    @Json(name = "inferred_tags")
    val inferredTags: kotlin.collections.List<kotlin.String>
)

