/**
* Runtime Common Library
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models

import com.squareup.moshi.Json

/**
 * This object holds description data that is returned from the code description model and set of filters that are used post-process the description.  
 * @param value 
 * @param embedding The transformer encoder embedding
 * @param confidence Confidence is a value between 0 and 1
 * @param filters 
 */

data class TLPDescription (
    @Json(name = "value")
    val value: kotlin.String,
    /* The transformer encoder embedding */
    @Json(name = "embedding")
    val embedding: kotlin.collections.List<java.math.BigDecimal>? = null,
    /* Confidence is a value between 0 and 1 */
    @Json(name = "confidence")
    val confidence: java.math.BigDecimal? = null,
    @Json(name = "filters")
    val filters: TLPDescriptionFilters? = null
)

