/**
* Runtime Common Library
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param result 
 * @param likelihood 
 * @param tokens The Tokenized input string. List of 32bit floats.
 * @param normalized This is the preprocessed string before tokenization.
 */

data class TLPNaturalLanguage (
    @Json(name = "result")
    val result: kotlin.Boolean,
    @Json(name = "likelihood")
    val likelihood: java.math.BigDecimal,
    /* The Tokenized input string. List of 32bit floats. */
    @Json(name = "tokens")
    val tokens: kotlin.collections.List<java.math.BigDecimal>,
    /* This is the preprocessed string before tokenization. */
    @Json(name = "normalized")
    val normalized: kotlin.String
)

