/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.SensitiveCategoryEnum
import org.openapitools.client.models.SensitiveSeverityEnum
import org.openapitools.client.models.TextMatch

import com.squareup.moshi.Json

/**
 * 
 * @param match 
 * @param severity 
 * @param description this is the description of the type of key we match with.
 * @param category 
 * @param schema 
 * @param entropy entropy of the sensitive
 */

data class TLPSensitive (
    @Json(name = "match")
    val match: TextMatch,
    @Json(name = "severity")
    val severity: SensitiveSeverityEnum,
    /* this is the description of the type of key we match with. */
    @Json(name = "description")
    val description: kotlin.String,
    @Json(name = "category")
    val category: SensitiveCategoryEnum,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    /* entropy of the sensitive */
    @Json(name = "entropy")
    val entropy: java.math.BigDecimal? = null
)

