/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models

import org.piecesapp.client.models.ReferencedAnchor
import org.piecesapp.client.models.ReferencedAnnotation
import org.piecesapp.client.models.ReferencedHint
import org.piecesapp.client.models.ReferencedPerson
import org.piecesapp.client.models.ReferencedSensitive
import org.piecesapp.client.models.ReferencedShare
import org.piecesapp.client.models.ReferencedTag
import org.piecesapp.client.models.ReferencedWebsite
import org.piecesapp.client.models.TrackedAssetEventCreationMetadata
import org.piecesapp.client.models.TrackedAssetEventFormatReclassificationMetadata
import org.piecesapp.client.models.TrackedAssetEventRenameMetadata
import org.piecesapp.client.models.TrackedAssetsEventSearchMetadata

import com.squareup.moshi.Json

/**
 * 
 * @param reclassification 
 * @param creation 
 * @param rename 
 * @param tag 
 * @param website 
 * @param person 
 * @param sensitive 
 * @param share 
 * @param search 
 * @param annotation 
 * @param hint 
 * @param anchor 
 */

data class TrackedAssetEventMetadata (
    @Json(name = "reclassification")
    val reclassification: TrackedAssetEventFormatReclassificationMetadata? = null,
    @Json(name = "creation")
    val creation: TrackedAssetEventCreationMetadata? = null,
    @Json(name = "rename")
    val rename: TrackedAssetEventRenameMetadata? = null,
    @Json(name = "tag")
    val tag: ReferencedTag? = null,
    @Json(name = "website")
    val website: ReferencedWebsite? = null,
    @Json(name = "person")
    val person: ReferencedPerson? = null,
    @Json(name = "sensitive")
    val sensitive: ReferencedSensitive? = null,
    @Json(name = "share")
    val share: ReferencedShare? = null,
    @Json(name = "search")
    val search: TrackedAssetsEventSearchMetadata? = null,
    @Json(name = "annotation")
    val annotation: ReferencedAnnotation? = null,
    @Json(name = "hint")
    val hint: ReferencedHint? = null,
    @Json(name = "anchor")
    val anchor: ReferencedAnchor? = null
)

