/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models


import com.squareup.moshi.Json

/**
 * If an asset was created from a file attachment
 * @param keyboard Whether the file was pasted via the keyboard
 * @param dragAndDrop Whether the file was dropped onto pieces
 * @param interaction Whether the file was attached via a button click
 */

data class TrackedAssetEventCreationMetadataFile (
    /* Whether the file was pasted via the keyboard */
    @Json(name = "keyboard")
    val keyboard: kotlin.Boolean? = null,
    /* Whether the file was dropped onto pieces */
    @Json(name = "drag_and_drop")
    val dragAndDrop: kotlin.Boolean? = null,
    /* Whether the file was attached via a button click */
    @Json(name = "interaction")
    val interaction: kotlin.Boolean? = null
)

