/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema

import com.squareup.moshi.Json

/**
 * This will give specific metadata need to determine what the rename was to/from.
 * @param previous 
 * @param current 
 * @param schema 
 */

data class TrackedAssetEventRenameMetadata (
    @Json(name = "previous")
    val previous: kotlin.String,
    @Json(name = "current")
    val current: kotlin.String,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null
)

