/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.TrackedAssetsEventSearchMetadataResults

import com.squareup.moshi.Json

/**
 * Metadata attached to a search event on an Asset
 * @param schema 
 * @param query The search query itself
 * @param results 
 */

data class TrackedAssetsEventSearchMetadata (
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    /* The search query itself */
    @Json(name = "query")
    val query: kotlin.String? = null,
    @Json(name = "results")
    val results: TrackedAssetsEventSearchMetadataResults? = null
)

