/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models

import org.piecesapp.client.models.EmbeddedModelSchema
import org.piecesapp.client.models.FlattenedAssets
import org.piecesapp.client.models.FlattenedPersons
import org.piecesapp.client.models.GroupedTimestamp
import org.piecesapp.client.models.MechanismEnum
import org.piecesapp.client.models.Score

import com.squareup.moshi.Json

/**
 * This is a specific model for related websites to an asset.
 * @param id 
 * @param url this is the actual website url.
 * @param name This is a name that is customized.
 * @param created 
 * @param updated 
 * @param schema 
 * @param assets 
 * @param deleted 
 * @param mechanisms This is a Map<String, MechanismEnum> where the the key is an asset id.
 * @param interactions This is an optional value that will keep track of the number of times this has been interacted with.
 * @param persons 
 * @param score 
 */

data class Website (
    @Json(name = "id")
    val id: kotlin.String,
    /* this is the actual website url. */
    @Json(name = "url")
    val url: kotlin.String,
    /* This is a name that is customized. */
    @Json(name = "name")
    val name: kotlin.String,
    @Json(name = "created")
    val created: GroupedTimestamp,
    @Json(name = "updated")
    val updated: GroupedTimestamp,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "assets")
    val assets: FlattenedAssets? = null,
    @Json(name = "deleted")
    val deleted: GroupedTimestamp? = null,
    /* This is a Map<String, MechanismEnum> where the the key is an asset id. */
    @Json(name = "mechanisms")
    val mechanisms: kotlin.collections.Map<kotlin.String, MechanismEnum>? = null,
    /* This is an optional value that will keep track of the number of times this has been interacted with. */
    @Json(name = "interactions")
    val interactions: kotlin.Int? = null,
    @Json(name = "persons")
    val persons: FlattenedPersons? = null,
    @Json(name = "score")
    val score: Score? = null
)

