/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.UpdatingStatusEnum

import com.squareup.moshi.Json

/**
 * This is the returnable for /os/update/check
 * @param status 
 * @param schema 
 */

data class CheckedOSUpdate (
    @Json(name = "status")
    val status: UpdatingStatusEnum,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null
)

