/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models


import com.squareup.moshi.Json

/**
* This will describe the sentiment of a specific message ie if the message was liked/disliked/reported
* Values: lIKE,dISLIKE,rEPORT
*/

enum class ConversationMessageSentimentEnum(val value: kotlin.String){


    @Json(name = "LIKE")
    lIKE("LIKE"),


    @Json(name = "DISLIKE")
    dISLIKE("DISLIKE"),


    @Json(name = "REPORT")
    rEPORT("REPORT");



    /**
    This override toString avoids using the enum var name and uses the actual api value instead.
    In cases the var name and value are different, the client would send incorrect enums to the server.
    **/
    override fun toString(): String {
        return value
    }

}

