/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models

import org.piecesapp.client.models.DiscoveredAssets
import org.piecesapp.client.models.EmbeddedModelSchema

import com.squareup.moshi.Json

/**
 * This will return assets that were extracted from the html webpage. This will contain the original url so you can double check the results wtih the results you passed in, but it will remain in the same order that it was passed in if used within the /discover/discover/html/webpage endpoint.
 * @param assets 
 * @param url 
 * @param schema 
 */

data class DiscoveredHtmlWebpage (
    @Json(name = "assets")
    val assets: DiscoveredAssets,
    @Json(name = "url")
    val url: kotlin.String,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null
)

