/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models

import org.piecesapp.client.models.EmbeddedModelSchema
import org.piecesapp.client.models.SeededSensitive

import com.squareup.moshi.Json

/**
 * This will return a discoveredSensitive, with a seed that can be used to create if automatic is set to false. and will provide the original text provided.
 * @param seed 
 * @param text 
 * @param schema 
 */

data class DiscoveredSensitive (
    @Json(name = "seed")
    val seed: SeededSensitive,
    @Json(name = "text")
    val text: kotlin.String,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null
)

