/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models

import org.piecesapp.client.models.GroupedTimestamp
import org.piecesapp.client.models.Model

import com.squareup.moshi.Json

/**
 * 
 * @param raw this is the raw value of the embedding
 * @param model 
 * @param created 
 * @param updated 
 * @param deleted 
 */

data class Embedding (
    /* this is the raw value of the embedding */
    @Json(name = "raw")
    val raw: kotlin.collections.List<java.math.BigDecimal>,
    @Json(name = "model")
    val model: Model,
    @Json(name = "created")
    val created: GroupedTimestamp,
    @Json(name = "updated")
    val updated: GroupedTimestamp,
    @Json(name = "deleted")
    val deleted: GroupedTimestamp? = null
)

