/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
* This is an enum that will highlight something that is externally sourced.
* Values: tWITTER,mEDIUM,lINKEDIN,iNSTAGRAM,fACEBOOK,rEDDIT,dISCORD,bITBUCKET,gITLAB,gITHUB,sLACK,mAILGUN
*/

enum class ExternallySourcedEnum(val value: kotlin.String){


    @Json(name = "TWITTER")
    tWITTER("TWITTER"),


    @Json(name = "MEDIUM")
    mEDIUM("MEDIUM"),


    @Json(name = "LINKED_IN")
    lINKEDIN("LINKED_IN"),


    @Json(name = "INSTAGRAM")
    iNSTAGRAM("INSTAGRAM"),


    @Json(name = "FACEBOOK")
    fACEBOOK("FACEBOOK"),


    @Json(name = "REDDIT")
    rEDDIT("REDDIT"),


    @Json(name = "DISCORD")
    dISCORD("DISCORD"),


    @Json(name = "BIT_BUCKET")
    bITBUCKET("BIT_BUCKET"),


    @Json(name = "GIT_LAB")
    gITLAB("GIT_LAB"),


    @Json(name = "GIT_HUB")
    gITHUB("GIT_HUB"),


    @Json(name = "SLACK")
    sLACK("SLACK"),


    @Json(name = "MAILGUN")
    mAILGUN("MAILGUN");



    /**
    This override toString avoids using the enum var name and uses the actual api value instead.
    In cases the var name and value are different, the client would send incorrect enums to the server.
    **/
    override fun toString(): String {
        return value
    }

}

