/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models

import org.piecesapp.client.models.EmbeddedModelSchema

import com.squareup.moshi.Json

/**
 * This will describe the font that the user sees.
 * @param size 
 * @param schema 
 */

data class Font (
    @Json(name = "size")
    val size: kotlin.Int,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null
)

