/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models

import org.piecesapp.client.models.ClassificationGenericEnum
import org.piecesapp.client.models.ClassificationSpecificEnum
import org.piecesapp.client.models.EmbeddedModelSchema

import com.squareup.moshi.Json

/**
 * FormatMetric  This is a model that will represent the about of specific formats. ie Generic: 'CODE' specific: 'DART' identifiers: ['FormatUID1, 'FormatUID2']
 * @param generic 
 * @param specific 
 * @param identifiers this is a list of format ids
 * @param schema 
 */

data class FormatMetric (
    @Json(name = "generic")
    val generic: ClassificationGenericEnum,
    @Json(name = "specific")
    val specific: ClassificationSpecificEnum,
    /* this is a list of format ids */
    @Json(name = "identifiers")
    val identifiers: kotlin.collections.List<kotlin.String>,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null
)

