/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema

import com.squareup.moshi.Json

/**
 * A helper classs to wrap Date-Time Values with Useful Helper Properties
 * @param value 
 * @param schema 
 * @param readable 
 */

data class GroupedTimestamp (
    @Json(name = "value")
    val value: java.time.OffsetDateTime,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "readable")
    val readable: kotlin.String? = null
)

