/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.Auth0OpenAIUserMetadata
import org.openapitools.client.models.EmbeddedModelSchema

import com.squareup.moshi.Json

/**
 * This is the input model for /external_provider/api_key/create
 * @param user This is the ID of the User.
 * @param schema 
 * @param openAI 
 */

data class PrecreatedExternalProviderApiKey (
    /* This is the ID of the User. */
    @Json(name = "user")
    val user: kotlin.String,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "open_AI")
    val openAI: Auth0OpenAIUserMetadata? = null
)

