/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.models

import org.piecesapp.client.models.EmbeddedModelSchema

import com.squareup.moshi.Json

/**
 * 
 * @param schema 
 * @param database This is an optional boolen that will tell us to use our entire snippet database as the sample.
 * @param question This is an optional boolean, that will let the serve know if you want to combine the 2 endpointsboth relevance && the Question endpoint to return the final results.
 */

data class QGPTRelevanceInputOptions (
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    /* This is an optional boolen that will tell us to use our entire snippet database as the sample. */
    @Json(name = "database")
    val database: kotlin.Boolean? = null,
    /* This is an optional boolean, that will let the serve know if you want to combine the 2 endpointsboth relevance && the Question endpoint to return the final results. */
    @Json(name = "question")
    val question: kotlin.Boolean? = null
)

