/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema

import com.squareup.moshi.Json

/**
 * This is specific for all the related materials, like people, tags, websites... xyz
 * @param schema 
 * @param people optional bool, that will say if we reccomend to run related.people on this conversation, IFF set to TRUE.
 */

data class QGPTAgentRelatedRoutes (
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    /* optional bool, that will say if we reccomend to run related.people on this conversation, IFF set to TRUE. */
    @Json(name = "people")
    val people: kotlin.Boolean? = null
)

