/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema

import com.squareup.moshi.Json

/**
 * This is a specific Model for the SeededAsset that will enable the developer to modify the enrichment levels of persons, tags, websites.  These enrichment levels will guarentee that the # of people/tags/websites do not eceeed the provided value, but will not guarentee a minimum.
 * @param schema 
 * @param tags 
 * @param websites 
 * @param persons 
 * @param hints 
 */

data class SeededAssetEnrichment (
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "tags")
    val tags: kotlin.Int? = null,
    @Json(name = "websites")
    val websites: kotlin.Int? = null,
    @Json(name = "persons")
    val persons: kotlin.Int? = null,
    @Json(name = "hints")
    val hints: kotlin.Int? = null
)

