/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.ReferencedConversation
import org.openapitools.client.models.TrackedConversationEventIdentifierDescriptionPairs
import org.openapitools.client.models.TrackedConversationEventMetadata

import com.squareup.moshi.Json

/**
 * This is a pre-created(seed) TrackedConversationEvent
 * @param identifierDescriptionPair 
 * @param conversation 
 * @param schema 
 * @param metadata 
 */

data class SeededTrackedConversationEvent (
    @Json(name = "identifier_description_pair")
    val identifierDescriptionPair: TrackedConversationEventIdentifierDescriptionPairs,
    @Json(name = "conversation")
    val conversation: ReferencedConversation,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "metadata")
    val metadata: TrackedConversationEventMetadata? = null
)

