/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * Append any additional parameter to the end of your request, and it will be sent to the provider. For example, access_type=offline (for Google Refresh Tokens) , display=popup (for Windows Live popup mode).
 * @param accessType 
 * @param display 
 */

data class SeededPKCEADDITIONALPARAMETERS (
    @Json(name = "access_type")
    val accessType: SeededPKCEADDITIONALPARAMETERS.AccessType? = null,
    @Json(name = "display")
    val display: SeededPKCEADDITIONALPARAMETERS.Display? = null
) {

    /**
    * 
    * Values: offline
    */
    
    enum class AccessType(val value: kotlin.String){
        @Json(name = "offline") offline("offline");
    }
    /**
    * 
    * Values: popup
    */
    
    enum class Display(val value: kotlin.String){
        @Json(name = "popup") popup("popup");
    }
}

