/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.SegmentedTechnicalLanguageFragment

import com.squareup.moshi.Json

/**
 * This is the output model for '/machine_learning/text/technical_language/parsers/segmentation'  This will have an iterable of the segmented Technical language text/code
 * @param iterable 
 * @param schema 
 */

data class SegmentedTechnicalLanguage (
    @Json(name = "iterable")
    val iterable: kotlin.collections.List<SegmentedTechnicalLanguageFragment>,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null
)

