/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.EmbeddedModelSchema
import org.openapitools.client.models.Score
import org.openapitools.client.models.Share

import com.squareup.moshi.Json

/**
 * this is just an iterable of our individual share models.
 * @param iterable this is just an iterable of our individual share models.
 * @param schema 
 * @param score 
 */

data class Shares (
    /* this is just an iterable of our individual share models. */
    @Json(name = "iterable")
    val iterable: kotlin.collections.List<Share>,
    @Json(name = "schema")
    val schema: EmbeddedModelSchema? = null,
    @Json(name = "score")
    val score: Score? = null
)

