/**
* Pieces Isomorphic OpenAPI
* Endpoints for Assets, Formats, Users, Asset, Format, User.
*
* The version of the OpenAPI document: 1.0
* Contact: tsavo@pieces.app
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
* This is a simple enum used to determine the status of the Updating process.(of PiecesOS)  UpdatingStatusEnum(READY_TO_RESTART, AVAILABLE(but not downloaded), DOWNLOADING, UNKNOWN, UP_TO_DATE)  UNKNOWN: should never be the case  These are some enums that are currently not implemented but are for future support( REINSTALL_REQUIRED, CONTACT_SUPPORT)
* Values: rEADYTORESTART,aVAILABLE,dOWNLOADING,uNKNOWN,uPTODATE,rEINSTALLREQUIRED,cONTACTSUPPORT
*/

enum class UpdatingStatusEnum(val value: kotlin.String){


    @Json(name = "READY_TO_RESTART")
    rEADYTORESTART("READY_TO_RESTART"),


    @Json(name = "AVAILABLE")
    aVAILABLE("AVAILABLE"),


    @Json(name = "DOWNLOADING")
    dOWNLOADING("DOWNLOADING"),


    @Json(name = "UNKNOWN")
    uNKNOWN("UNKNOWN"),


    @Json(name = "UP_TO_DATE")
    uPTODATE("UP_TO_DATE"),


    @Json(name = "REINSTALL_REQUIRED")
    rEINSTALLREQUIRED("REINSTALL_REQUIRED"),


    @Json(name = "CONTACT_SUPPORT")
    cONTACTSUPPORT("CONTACT_SUPPORT");



    /**
    This override toString avoids using the enum var name and uses the actual api value instead.
    In cases the var name and value are different, the client would send incorrect enums to the server.
    **/
    override fun toString(): String {
        return value
    }

}

