/**
* Runtime Common Library
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.apis


import com.squareup.moshi.Json

/**
 * This object holds a set of filters that were applied to the description model. The iterable is an array of unique filters.
 * @param iterable 
 */

data class TLPDescriptionFilters (
    @Json(name = "iterable")
    val iterable: kotlin.collections.List<TLPDescriptionFilter>
)

