/**
* Runtime Common Library
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.apis


import com.squareup.moshi.Json

/**
 * 
 * @param urls 
 * @param emails 
 * @param users 
 */

data class TLPLinks (
    @Json(name = "urls")
    val urls: kotlin.collections.List<kotlin.String>,
    @Json(name = "emails")
    val emails: kotlin.collections.List<kotlin.String>,
    @Json(name = "users")
    val users: kotlin.collections.List<kotlin.String>
)

