/**
* Runtime Common Library
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.apis


import com.squareup.moshi.Json

/**
 * current here is a key to the current language in the lookup property.
 * @param likelihood 
 * @param current 
 * @param lookup 
 */

data class TLPLanguage (
    @Json(name = "likelihood")
    val likelihood: java.math.BigDecimal,
    @Json(name = "current")
    val current: kotlin.String,
    @Json(name = "lookup")
    val lookup: TLPLanguageMap
)

