/**
* Runtime Common Library
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.apis


import com.squareup.moshi.Json

/**
 * This is a fully referenced representation of a sensitive pieces of data.
 * @param id 
 * @param match 
 * @param category 
 * @param severity 
 * @param description 
 * @param metadata 
 */

data class TLPSensitive (
    @Json(name = "id")
    val id: kotlin.String,
    @Json(name = "match")
    val match: TLPTextMatch,
    @Json(name = "category")
    val category: TLPSensitiveCategoryEnum,
    @Json(name = "severity")
    val severity: TLPSensitiveSeverityEnum,
    @Json(name = "description")
    val description: kotlin.String,
    @Json(name = "metadata")
    val metadata: TLPSensitiveMetadata? = null
)

