/**
* Runtime Common Library
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.piecesapp.client.apis


import com.squareup.moshi.Json

/**
 * This is optional metatdata attached to a sensitive piece of data.
 * @param match 
 * @param entropy entropy of the sensitive
 */

data class TLPSensitiveMetadata (
    @Json(name = "match")
    val match: TLPTextMatch? = null,
    /* entropy of the sensitive */
    @Json(name = "entropy")
    val entropy: java.math.BigDecimal? = null
)

